version: '3'
services:
    db:
        image: mysql:5.7
        restart: unless-stopped
        container_name: tpbs_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: tpbs
        volumes:
            - ./db:/var/lib/mysql
    tpbs_backend:
        restart: on-failure
        image: registry.octagoncorp.com/tpbank/tpsecuritybackend:0.0.4
        command: >
            sh -c "python tpbs/manage.py migrate --settings=tpbs.production &&
            python tpbs/manage.py loaddata users.json --settings=tpbs.production &&
            python tpbs/manage.py runserver --settings=tpbs.production 0.0.0.0:8000"
        ports:
            - "8000:8000"
        links:
            - db
        depends_on:
            - db
        volumes:
            - ./uploads:/www/tpbs/static/uploads/
